### ISSUE TITLE
Unexpected error from the server 408

### ISSUE THREAD

**Issue by polenvinagre** [FlutterFlow/flutterflow-cli#2]
Hi, I am receiving error

Unexpected error from the server.
Status: 408
Body: Error: could not handle the request

This is the request:
flutterflow export-code --project mydXXX-YYYYY --dest C:\dev\flutter_projects\dartpub --[no-]include-assets --token 111111-11111-111111-1111

**Comment by aemelyanovff** [comment]
I need project id to to troubleshoot the issue. Please email it to anton [at] flutterflow.io.

**Comment by aemelyanovff** [comment]
Replied offline.
